#!/bin/bash

# Get the PID of the Gunicorn master process
PID=$(pgrep gunicorn)

if [[ -n $PID ]]; then
    echo "Reloading Gunicorn gracefully..."

    # Send a signal to gracefully reload Gunicorn
    kill -HUP $PID

    echo "Gunicorn reloaded."
else
    echo "Gunicorn is not running."
fi
